// This file is generated by rust-protobuf 2.8.1. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `kv.proto`

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_8_1;

#[derive(PartialEq,Clone,Default)]
pub struct KeyValue {
    // message fields
    pub key: ::std::vec::Vec<u8>,
    pub create_revision: i64,
    pub mod_revision: i64,
    pub version: i64,
    pub value: ::std::vec::Vec<u8>,
    pub lease: i64,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a KeyValue {
    fn default() -> &'a KeyValue {
        <KeyValue as ::protobuf::Message>::default_instance()
    }
}

impl KeyValue {
    pub fn new() -> KeyValue {
        ::std::default::Default::default()
    }

    // bytes key = 1;


    pub fn get_key(&self) -> &[u8] {
        &self.key
    }
    pub fn clear_key(&mut self) {
        self.key.clear();
    }

    // Param is passed by value, moved
    pub fn set_key(&mut self, v: ::std::vec::Vec<u8>) {
        self.key = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_key(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.key
    }

    // Take field
    pub fn take_key(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.key, ::std::vec::Vec::new())
    }

    // int64 create_revision = 2;


    pub fn get_create_revision(&self) -> i64 {
        self.create_revision
    }
    pub fn clear_create_revision(&mut self) {
        self.create_revision = 0;
    }

    // Param is passed by value, moved
    pub fn set_create_revision(&mut self, v: i64) {
        self.create_revision = v;
    }

    // int64 mod_revision = 3;


    pub fn get_mod_revision(&self) -> i64 {
        self.mod_revision
    }
    pub fn clear_mod_revision(&mut self) {
        self.mod_revision = 0;
    }

    // Param is passed by value, moved
    pub fn set_mod_revision(&mut self, v: i64) {
        self.mod_revision = v;
    }

    // int64 version = 4;


    pub fn get_version(&self) -> i64 {
        self.version
    }
    pub fn clear_version(&mut self) {
        self.version = 0;
    }

    // Param is passed by value, moved
    pub fn set_version(&mut self, v: i64) {
        self.version = v;
    }

    // bytes value = 5;


    pub fn get_value(&self) -> &[u8] {
        &self.value
    }
    pub fn clear_value(&mut self) {
        self.value.clear();
    }

    // Param is passed by value, moved
    pub fn set_value(&mut self, v: ::std::vec::Vec<u8>) {
        self.value = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_value(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.value
    }

    // Take field
    pub fn take_value(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.value, ::std::vec::Vec::new())
    }

    // int64 lease = 6;


    pub fn get_lease(&self) -> i64 {
        self.lease
    }
    pub fn clear_lease(&mut self) {
        self.lease = 0;
    }

    // Param is passed by value, moved
    pub fn set_lease(&mut self, v: i64) {
        self.lease = v;
    }
}

impl ::protobuf::Message for KeyValue {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.key)?;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.create_revision = tmp;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.mod_revision = tmp;
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.version = tmp;
                },
                5 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.value)?;
                },
                6 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.lease = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.key.is_empty() {
            my_size += ::protobuf::rt::bytes_size(1, &self.key);
        }
        if self.create_revision != 0 {
            my_size += ::protobuf::rt::value_size(2, self.create_revision, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.mod_revision != 0 {
            my_size += ::protobuf::rt::value_size(3, self.mod_revision, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.version != 0 {
            my_size += ::protobuf::rt::value_size(4, self.version, ::protobuf::wire_format::WireTypeVarint);
        }
        if !self.value.is_empty() {
            my_size += ::protobuf::rt::bytes_size(5, &self.value);
        }
        if self.lease != 0 {
            my_size += ::protobuf::rt::value_size(6, self.lease, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.key.is_empty() {
            os.write_bytes(1, &self.key)?;
        }
        if self.create_revision != 0 {
            os.write_int64(2, self.create_revision)?;
        }
        if self.mod_revision != 0 {
            os.write_int64(3, self.mod_revision)?;
        }
        if self.version != 0 {
            os.write_int64(4, self.version)?;
        }
        if !self.value.is_empty() {
            os.write_bytes(5, &self.value)?;
        }
        if self.lease != 0 {
            os.write_int64(6, self.lease)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> KeyValue {
        KeyValue::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "key",
                    |m: &KeyValue| { &m.key },
                    |m: &mut KeyValue| { &mut m.key },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                    "create_revision",
                    |m: &KeyValue| { &m.create_revision },
                    |m: &mut KeyValue| { &mut m.create_revision },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                    "mod_revision",
                    |m: &KeyValue| { &m.mod_revision },
                    |m: &mut KeyValue| { &mut m.mod_revision },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                    "version",
                    |m: &KeyValue| { &m.version },
                    |m: &mut KeyValue| { &mut m.version },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "value",
                    |m: &KeyValue| { &m.value },
                    |m: &mut KeyValue| { &mut m.value },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                    "lease",
                    |m: &KeyValue| { &m.lease },
                    |m: &mut KeyValue| { &mut m.lease },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<KeyValue>(
                    "KeyValue",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static KeyValue {
        static mut instance: ::protobuf::lazy::Lazy<KeyValue> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const KeyValue,
        };
        unsafe {
            instance.get(KeyValue::new)
        }
    }
}

impl ::protobuf::Clear for KeyValue {
    fn clear(&mut self) {
        self.key.clear();
        self.create_revision = 0;
        self.mod_revision = 0;
        self.version = 0;
        self.value.clear();
        self.lease = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for KeyValue {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for KeyValue {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct Event {
    // message fields
    pub field_type: Event_EventType,
    pub kv: ::protobuf::SingularPtrField<KeyValue>,
    pub prev_kv: ::protobuf::SingularPtrField<KeyValue>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Event {
    fn default() -> &'a Event {
        <Event as ::protobuf::Message>::default_instance()
    }
}

impl Event {
    pub fn new() -> Event {
        ::std::default::Default::default()
    }

    // .mvccpb.Event.EventType type = 1;


    pub fn get_field_type(&self) -> Event_EventType {
        self.field_type
    }
    pub fn clear_field_type(&mut self) {
        self.field_type = Event_EventType::PUT;
    }

    // Param is passed by value, moved
    pub fn set_field_type(&mut self, v: Event_EventType) {
        self.field_type = v;
    }

    // .mvccpb.KeyValue kv = 2;


    pub fn get_kv(&self) -> &KeyValue {
        self.kv.as_ref().unwrap_or_else(|| KeyValue::default_instance())
    }
    pub fn clear_kv(&mut self) {
        self.kv.clear();
    }

    pub fn has_kv(&self) -> bool {
        self.kv.is_some()
    }

    // Param is passed by value, moved
    pub fn set_kv(&mut self, v: KeyValue) {
        self.kv = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_kv(&mut self) -> &mut KeyValue {
        if self.kv.is_none() {
            self.kv.set_default();
        }
        self.kv.as_mut().unwrap()
    }

    // Take field
    pub fn take_kv(&mut self) -> KeyValue {
        self.kv.take().unwrap_or_else(|| KeyValue::new())
    }

    // .mvccpb.KeyValue prev_kv = 3;


    pub fn get_prev_kv(&self) -> &KeyValue {
        self.prev_kv.as_ref().unwrap_or_else(|| KeyValue::default_instance())
    }
    pub fn clear_prev_kv(&mut self) {
        self.prev_kv.clear();
    }

    pub fn has_prev_kv(&self) -> bool {
        self.prev_kv.is_some()
    }

    // Param is passed by value, moved
    pub fn set_prev_kv(&mut self, v: KeyValue) {
        self.prev_kv = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_prev_kv(&mut self) -> &mut KeyValue {
        if self.prev_kv.is_none() {
            self.prev_kv.set_default();
        }
        self.prev_kv.as_mut().unwrap()
    }

    // Take field
    pub fn take_prev_kv(&mut self) -> KeyValue {
        self.prev_kv.take().unwrap_or_else(|| KeyValue::new())
    }
}

impl ::protobuf::Message for Event {
    fn is_initialized(&self) -> bool {
        for v in &self.kv {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.prev_kv {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.field_type, 1, &mut self.unknown_fields)?
                },
                2 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.kv)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.prev_kv)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.field_type != Event_EventType::PUT {
            my_size += ::protobuf::rt::enum_size(1, self.field_type);
        }
        if let Some(ref v) = self.kv.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if let Some(ref v) = self.prev_kv.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.field_type != Event_EventType::PUT {
            os.write_enum(1, self.field_type.value())?;
        }
        if let Some(ref v) = self.kv.as_ref() {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if let Some(ref v) = self.prev_kv.as_ref() {
            os.write_tag(3, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Event {
        Event::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<Event_EventType>>(
                    "type",
                    |m: &Event| { &m.field_type },
                    |m: &mut Event| { &mut m.field_type },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<KeyValue>>(
                    "kv",
                    |m: &Event| { &m.kv },
                    |m: &mut Event| { &mut m.kv },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<KeyValue>>(
                    "prev_kv",
                    |m: &Event| { &m.prev_kv },
                    |m: &mut Event| { &mut m.prev_kv },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<Event>(
                    "Event",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static Event {
        static mut instance: ::protobuf::lazy::Lazy<Event> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const Event,
        };
        unsafe {
            instance.get(Event::new)
        }
    }
}

impl ::protobuf::Clear for Event {
    fn clear(&mut self) {
        self.field_type = Event_EventType::PUT;
        self.kv.clear();
        self.prev_kv.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Event {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Event {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
pub enum Event_EventType {
    PUT = 0,
    DELETE = 1,
}

impl ::protobuf::ProtobufEnum for Event_EventType {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<Event_EventType> {
        match value {
            0 => ::std::option::Option::Some(Event_EventType::PUT),
            1 => ::std::option::Option::Some(Event_EventType::DELETE),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [Event_EventType] = &[
            Event_EventType::PUT,
            Event_EventType::DELETE,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::EnumDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                ::protobuf::reflect::EnumDescriptor::new("Event_EventType", file_descriptor_proto())
            })
        }
    }
}

impl ::std::marker::Copy for Event_EventType {
}

impl ::std::default::Default for Event_EventType {
    fn default() -> Self {
        Event_EventType::PUT
    }
}

impl ::protobuf::reflect::ProtobufValue for Event_EventType {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Enum(self.descriptor())
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x08kv.proto\x12\x06mvccpb\"\xae\x01\n\x08KeyValue\x12\x10\n\x03key\
    \x18\x01\x20\x01(\x0cR\x03key\x12'\n\x0fcreate_revision\x18\x02\x20\x01(\
    \x03R\x0ecreateRevision\x12!\n\x0cmod_revision\x18\x03\x20\x01(\x03R\x0b\
    modRevision\x12\x18\n\x07version\x18\x04\x20\x01(\x03R\x07version\x12\
    \x14\n\x05value\x18\x05\x20\x01(\x0cR\x05value\x12\x14\n\x05lease\x18\
    \x06\x20\x01(\x03R\x05lease\"\xa3\x01\n\x05Event\x12+\n\x04type\x18\x01\
    \x20\x01(\x0e2\x17.mvccpb.Event.EventTypeR\x04type\x12\x20\n\x02kv\x18\
    \x02\x20\x01(\x0b2\x10.mvccpb.KeyValueR\x02kv\x12)\n\x07prev_kv\x18\x03\
    \x20\x01(\x0b2\x10.mvccpb.KeyValueR\x06prevKv\"\x20\n\tEventType\x12\x07\
    \n\x03PUT\x10\0\x12\n\n\x06DELETE\x10\x01B\x15\n\x11io.etcd.jetcd.apiP\
    \x01J\x9e\x13\n\x06\x12\x04\x10\0<\x01\n\xc5\x04\n\x01\x0c\x12\x03\x10\0\
    \x122\xba\x04\n\x20Copyright\x202017\x20The\x20jetcd\x20authors\n\n\x20L\
    icensed\x20under\x20the\x20Apache\x20License,\x20Version\x202.0\x20(the\
    \x20\"License\");\n\x20you\x20may\x20not\x20use\x20this\x20file\x20excep\
    t\x20in\x20compliance\x20with\x20the\x20License.\n\x20You\x20may\x20obta\
    in\x20a\x20copy\x20of\x20the\x20License\x20at\n\n\x20\x20\x20\x20\x20htt\
    p://www.apache.org/licenses/LICENSE-2.0\n\n\x20Unless\x20required\x20by\
    \x20applicable\x20law\x20or\x20agreed\x20to\x20in\x20writing,\x20softwar\
    e\n\x20distributed\x20under\x20the\x20License\x20is\x20distributed\x20on\
    \x20an\x20\"AS\x20IS\"\x20BASIS,\n\x20WITHOUT\x20WARRANTIES\x20OR\x20CON\
    DITIONS\x20OF\x20ANY\x20KIND,\x20either\x20express\x20or\x20implied.\n\
    \x20See\x20the\x20License\x20for\x20the\x20specific\x20language\x20gover\
    ning\x20permissions\x20and\n\x20limitations\x20under\x20the\x20License.\
    \n\n\n\x08\n\x01\x02\x12\x03\x12\0\x0f\n\x08\n\x01\x08\x12\x03\x14\0\"\n\
    \t\n\x02\x08\n\x12\x03\x14\0\"\n\x08\n\x01\x08\x12\x03\x15\0*\n\t\n\x02\
    \x08\x01\x12\x03\x15\0*\n\n\n\x02\x04\0\x12\x04\x17\0(\x01\n\n\n\x03\x04\
    \0\x01\x12\x03\x17\x08\x10\nD\n\x04\x04\0\x02\0\x12\x03\x19\x02\x10\x1a7\
    \x20key\x20is\x20the\x20key\x20in\x20bytes.\x20An\x20empty\x20key\x20is\
    \x20not\x20allowed.\n\n\r\n\x05\x04\0\x02\0\x04\x12\x04\x19\x02\x17\x12\
    \n\x0c\n\x05\x04\0\x02\0\x05\x12\x03\x19\x02\x07\n\x0c\n\x05\x04\0\x02\0\
    \x01\x12\x03\x19\x08\x0b\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x19\x0e\x0f\
    \nL\n\x04\x04\0\x02\x01\x12\x03\x1b\x02\x1c\x1a?\x20create_revision\x20i\
    s\x20the\x20revision\x20of\x20last\x20creation\x20on\x20this\x20key.\n\n\
    \r\n\x05\x04\0\x02\x01\x04\x12\x04\x1b\x02\x19\x10\n\x0c\n\x05\x04\0\x02\
    \x01\x05\x12\x03\x1b\x02\x07\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\x1b\
    \x08\x17\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03\x1b\x1a\x1b\nM\n\x04\x04\
    \0\x02\x02\x12\x03\x1d\x02\x19\x1a@\x20mod_revision\x20is\x20the\x20revi\
    sion\x20of\x20last\x20modification\x20on\x20this\x20key.\n\n\r\n\x05\x04\
    \0\x02\x02\x04\x12\x04\x1d\x02\x1b\x1c\n\x0c\n\x05\x04\0\x02\x02\x05\x12\
    \x03\x1d\x02\x07\n\x0c\n\x05\x04\0\x02\x02\x01\x12\x03\x1d\x08\x14\n\x0c\
    \n\x05\x04\0\x02\x02\x03\x12\x03\x1d\x17\x18\n\x91\x01\n\x04\x04\0\x02\
    \x03\x12\x03!\x02\x14\x1a\x83\x01\x20version\x20is\x20the\x20version\x20\
    of\x20the\x20key.\x20A\x20deletion\x20resets\n\x20the\x20version\x20to\
    \x20zero\x20and\x20any\x20modification\x20of\x20the\x20key\n\x20increase\
    s\x20its\x20version.\n\n\r\n\x05\x04\0\x02\x03\x04\x12\x04!\x02\x1d\x19\
    \n\x0c\n\x05\x04\0\x02\x03\x05\x12\x03!\x02\x07\n\x0c\n\x05\x04\0\x02\
    \x03\x01\x12\x03!\x08\x0f\n\x0c\n\x05\x04\0\x02\x03\x03\x12\x03!\x12\x13\
    \n<\n\x04\x04\0\x02\x04\x12\x03#\x02\x12\x1a/\x20value\x20is\x20the\x20v\
    alue\x20held\x20by\x20the\x20key,\x20in\x20bytes.\n\n\r\n\x05\x04\0\x02\
    \x04\x04\x12\x04#\x02!\x14\n\x0c\n\x05\x04\0\x02\x04\x05\x12\x03#\x02\
    \x07\n\x0c\n\x05\x04\0\x02\x04\x01\x12\x03#\x08\r\n\x0c\n\x05\x04\0\x02\
    \x04\x03\x12\x03#\x10\x11\n\xb3\x01\n\x04\x04\0\x02\x05\x12\x03'\x02\x12\
    \x1a\xa5\x01\x20lease\x20is\x20the\x20ID\x20of\x20the\x20lease\x20that\
    \x20attached\x20to\x20key.\n\x20When\x20the\x20attached\x20lease\x20expi\
    res,\x20the\x20key\x20will\x20be\x20deleted.\n\x20If\x20lease\x20is\x200\
    ,\x20then\x20no\x20lease\x20is\x20attached\x20to\x20the\x20key.\n\n\r\n\
    \x05\x04\0\x02\x05\x04\x12\x04'\x02#\x12\n\x0c\n\x05\x04\0\x02\x05\x05\
    \x12\x03'\x02\x07\n\x0c\n\x05\x04\0\x02\x05\x01\x12\x03'\x08\r\n\x0c\n\
    \x05\x04\0\x02\x05\x03\x12\x03'\x10\x11\n\n\n\x02\x04\x01\x12\x04*\0<\
    \x01\n\n\n\x03\x04\x01\x01\x12\x03*\x08\r\n\x0c\n\x04\x04\x01\x04\0\x12\
    \x04+\x02.\x03\n\x0c\n\x05\x04\x01\x04\0\x01\x12\x03+\x07\x10\n\r\n\x06\
    \x04\x01\x04\0\x02\0\x12\x03,\x04\x0c\n\x0e\n\x07\x04\x01\x04\0\x02\0\
    \x01\x12\x03,\x04\x07\n\x0e\n\x07\x04\x01\x04\0\x02\0\x02\x12\x03,\n\x0b\
    \n\r\n\x06\x04\x01\x04\0\x02\x01\x12\x03-\x04\x0f\n\x0e\n\x07\x04\x01\
    \x04\0\x02\x01\x01\x12\x03-\x04\n\n\x0e\n\x07\x04\x01\x04\0\x02\x01\x02\
    \x12\x03-\r\x0e\n\xa7\x01\n\x04\x04\x01\x02\0\x12\x032\x02\x15\x1a\x99\
    \x01\x20type\x20is\x20the\x20kind\x20of\x20event.\x20If\x20type\x20is\
    \x20a\x20PUT,\x20it\x20indicates\n\x20new\x20data\x20has\x20been\x20stor\
    ed\x20to\x20the\x20key.\x20If\x20type\x20is\x20a\x20DELETE,\n\x20it\x20i\
    ndicates\x20the\x20key\x20was\x20deleted.\n\n\r\n\x05\x04\x01\x02\0\x04\
    \x12\x042\x02.\x03\n\x0c\n\x05\x04\x01\x02\0\x06\x12\x032\x02\x0b\n\x0c\
    \n\x05\x04\x01\x02\0\x01\x12\x032\x0c\x10\n\x0c\n\x05\x04\x01\x02\0\x03\
    \x12\x032\x13\x14\n\x8c\x02\n\x04\x04\x01\x02\x01\x12\x038\x02\x12\x1a\
    \xfe\x01\x20kv\x20holds\x20the\x20KeyValue\x20for\x20the\x20event.\n\x20\
    A\x20PUT\x20event\x20contains\x20current\x20kv\x20pair.\n\x20A\x20PUT\
    \x20event\x20with\x20kv.Version=1\x20indicates\x20the\x20creation\x20of\
    \x20a\x20key.\n\x20A\x20DELETE/EXPIRE\x20event\x20contains\x20the\x20del\
    eted\x20key\x20with\n\x20its\x20modification\x20revision\x20set\x20to\
    \x20the\x20revision\x20of\x20deletion.\n\n\r\n\x05\x04\x01\x02\x01\x04\
    \x12\x048\x022\x15\n\x0c\n\x05\x04\x01\x02\x01\x06\x12\x038\x02\n\n\x0c\
    \n\x05\x04\x01\x02\x01\x01\x12\x038\x0b\r\n\x0c\n\x05\x04\x01\x02\x01\
    \x03\x12\x038\x10\x11\nI\n\x04\x04\x01\x02\x02\x12\x03;\x02\x17\x1a<\x20\
    prev_kv\x20holds\x20the\x20key-value\x20pair\x20before\x20the\x20event\
    \x20happens.\n\n\r\n\x05\x04\x01\x02\x02\x04\x12\x04;\x028\x12\n\x0c\n\
    \x05\x04\x01\x02\x02\x06\x12\x03;\x02\n\n\x0c\n\x05\x04\x01\x02\x02\x01\
    \x12\x03;\x0b\x12\n\x0c\n\x05\x04\x01\x02\x02\x03\x12\x03;\x15\x16b\x06p\
    roto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
